const catalog = [
  {
    id: "dune-part-two",
    title: "Dune: Part Two",
    type: "movie",
    industry: "Hollywood",
    year: 2024,
    rating: 8.7,
    runtime: 166,
    language: "English",
    genres: ["sci-fi", "adventure", "drama"],
    moods: ["epic", "adventurous", "intense", "mind-bending"],
    platforms: ["netflix", "max"],
    isLatest: true,
    isTrending: true,
    palette: ["#a55b2a", "#f4c27d", "#3b1d0f"],
    hook: "Grand scale sci-fi with emotional weight and stunning world-building.",
    synopsis: "Paul Atreides rises into prophecy while war and destiny collide across the desert."
  },
  {
    id: "fall-guy",
    title: "The Fall Guy",
    type: "movie",
    industry: "Hollywood",
    year: 2024,
    rating: 7.1,
    runtime: 126,
    language: "English",
    genres: ["action", "comedy", "romance"],
    moods: ["funny", "adventurous", "feel-good", "energetic"],
    platforms: ["prime video", "apple tv+"],
    isLatest: true,
    isTrending: true,
    palette: ["#ffac33", "#ff5a5f", "#5d1d1f"],
    hook: "An action-comedy date-night pick with easy charm and stunt-fueled fun.",
    synopsis: "A stuntman is pulled into a mystery while trying to win back the filmmaker he loves."
  },
  {
    id: "inside-out-2",
    title: "Inside Out 2",
    type: "movie",
    industry: "Hollywood",
    year: 2024,
    rating: 7.9,
    runtime: 96,
    language: "English",
    genres: ["animation", "family", "comedy"],
    moods: ["feel-good", "family", "funny", "uplifting"],
    platforms: ["disney+"],
    isLatest: true,
    isTrending: true,
    palette: ["#5ad0ff", "#ffcc4d", "#6f5cff"],
    hook: "Bright, witty, and emotionally warm without feeling too heavy.",
    synopsis: "Riley's emotional world gets even more crowded when new feelings arrive."
  },
  {
    id: "furiosa",
    title: "Furiosa: A Mad Max Saga",
    type: "movie",
    industry: "Hollywood",
    year: 2024,
    rating: 7.6,
    runtime: 148,
    language: "English",
    genres: ["action", "adventure", "sci-fi"],
    moods: ["intense", "adventurous", "dark", "epic"],
    platforms: ["max"],
    isLatest: true,
    isTrending: true,
    palette: ["#bb4b1a", "#ffb54d", "#28110b"],
    hook: "A furious, stylish survival saga with relentless momentum.",
    synopsis: "Young Furiosa fights through a brutal wasteland to reclaim her freedom."
  },
  {
    id: "poor-things",
    title: "Poor Things",
    type: "movie",
    industry: "Hollywood",
    year: 2023,
    rating: 8.0,
    runtime: 141,
    language: "English",
    genres: ["fantasy", "romance", "comedy"],
    moods: ["quirky", "mind-bending", "romantic", "bold"],
    platforms: ["disney+", "hulu"],
    isLatest: true,
    isTrending: false,
    palette: ["#78d0f5", "#f26ca7", "#17213f"],
    hook: "A wildly original watch for anyone wanting strange, clever, and visually rich cinema.",
    synopsis: "A woman embarks on a surreal journey of discovery, freedom, and reinvention."
  },
  {
    id: "interstellar",
    title: "Interstellar",
    type: "movie",
    industry: "Hollywood",
    year: 2014,
    rating: 8.7,
    runtime: 169,
    language: "English",
    genres: ["sci-fi", "drama", "adventure"],
    moods: ["mind-bending", "inspirational", "emotional", "epic"],
    platforms: ["netflix", "prime video"],
    isLatest: false,
    isTrending: true,
    palette: ["#31465e", "#d3c3a8", "#101722"],
    hook: "A beautiful choice when you want smart sci-fi with emotion and scale.",
    synopsis: "A desperate space mission becomes a moving story about love, time, and survival."
  },
  {
    id: "knives-out",
    title: "Knives Out",
    type: "movie",
    industry: "Hollywood",
    year: 2019,
    rating: 7.9,
    runtime: 130,
    language: "English",
    genres: ["mystery", "comedy", "crime"],
    moods: ["funny", "smart", "stylish", "cozy"],
    platforms: ["netflix", "prime video"],
    isLatest: false,
    isTrending: true,
    palette: ["#9c5738", "#f3cf92", "#2e1c17"],
    hook: "A clever and cozy mystery with just the right amount of bite.",
    synopsis: "A detective investigates a wealthy family's secrets after a shocking death."
  },
  {
    id: "past-lives",
    title: "Past Lives",
    type: "movie",
    industry: "Hollywood",
    year: 2023,
    rating: 8.0,
    runtime: 106,
    language: "English",
    genres: ["romance", "drama"],
    moods: ["romantic", "sad", "emotional", "reflective"],
    platforms: ["prime video"],
    isLatest: true,
    isTrending: false,
    palette: ["#7d8cc4", "#f0b68a", "#24203f"],
    hook: "Quiet, mature, and deeply affecting for a more intimate mood.",
    synopsis: "Two childhood friends reconnect years later and confront what might have been."
  },
  {
    id: "spider-verse",
    title: "Spider-Man: Across the Spider-Verse",
    type: "movie",
    industry: "Hollywood",
    year: 2023,
    rating: 8.6,
    runtime: 140,
    language: "English",
    genres: ["animation", "action", "sci-fi"],
    moods: ["adventurous", "energetic", "uplifting", "mind-bending"],
    platforms: ["netflix", "prime video"],
    isLatest: true,
    isTrending: true,
    palette: ["#ff4f81", "#5f9bff", "#22103d"],
    hook: "An electric blend of heart, color, and multiverse energy.",
    synopsis: "Miles Morales leaps across dimensions where every decision changes his future."
  },
  {
    id: "laapataa-ladies",
    title: "Laapataa Ladies",
    type: "movie",
    industry: "Bollywood",
    year: 2024,
    rating: 8.4,
    runtime: 124,
    language: "Hindi",
    genres: ["comedy", "drama"],
    moods: ["feel-good", "funny", "smart", "uplifting"],
    platforms: ["netflix"],
    isLatest: true,
    isTrending: true,
    palette: ["#ecb96d", "#8bc9b4", "#4d2f27"],
    hook: "Warm, witty, and beautifully grounded with a fresh modern heart.",
    synopsis: "Two brides are accidentally swapped on a train journey, setting off a funny and moving chain of events."
  },
  {
    id: "12th-fail",
    title: "12th Fail",
    type: "movie",
    industry: "Bollywood",
    year: 2023,
    rating: 8.8,
    runtime: 147,
    language: "Hindi",
    genres: ["drama"],
    moods: ["inspirational", "emotional", "uplifting", "smart"],
    platforms: ["disney+"],
    isLatest: true,
    isTrending: true,
    palette: ["#6388c6", "#e7d1a2", "#1f2434"],
    hook: "A deeply inspiring underdog story that lands with honesty instead of melodrama.",
    synopsis: "A young man from a small town fights impossible odds while chasing a civil services dream."
  },
  {
    id: "zindagi-na-milegi-dobara",
    title: "Zindagi Na Milegi Dobara",
    type: "movie",
    industry: "Bollywood",
    year: 2011,
    rating: 8.2,
    runtime: 155,
    language: "Hindi",
    genres: ["adventure", "comedy", "drama"],
    moods: ["feel-good", "adventurous", "uplifting", "stylish"],
    platforms: ["netflix", "prime video"],
    isLatest: false,
    isTrending: true,
    palette: ["#3ea8c7", "#efb95b", "#163648"],
    hook: "A breezy, life-affirming friendship film that always feels good to revisit.",
    synopsis: "Three friends take a bachelor trip through Spain and end up confronting love, fear, and what they really want."
  },
  {
    id: "yeh-jawaani-hai-deewani",
    title: "Yeh Jawaani Hai Deewani",
    type: "movie",
    industry: "Bollywood",
    year: 2013,
    rating: 7.3,
    runtime: 160,
    language: "Hindi",
    genres: ["romance", "drama", "comedy"],
    moods: ["romantic", "feel-good", "stylish", "funny"],
    platforms: ["netflix"],
    isLatest: false,
    isTrending: true,
    palette: ["#ff9959", "#6f6dff", "#2f1e3c"],
    hook: "Big-hearted, breezy, and perfect when you want romance with energy and charm.",
    synopsis: "Old friends reconnect across years of ambition, travel, and unresolved love."
  },
  {
    id: "andhadhun",
    title: "Andhadhun",
    type: "movie",
    industry: "Bollywood",
    year: 2018,
    rating: 8.2,
    runtime: 139,
    language: "Hindi",
    genres: ["crime", "mystery", "thriller"],
    moods: ["dark", "smart", "intense", "mind-bending"],
    platforms: ["netflix"],
    isLatest: false,
    isTrending: true,
    palette: ["#6c5446", "#e8d1a6", "#1e1818"],
    hook: "A sharply written thriller that keeps twisting without losing its wicked sense of fun.",
    synopsis: "A blind pianist appears to witness a murder and gets trapped in a deliciously unpredictable game."
  },
  {
    id: "kahaani",
    title: "Kahaani",
    type: "movie",
    industry: "Bollywood",
    year: 2012,
    rating: 8.1,
    runtime: 122,
    language: "Hindi",
    genres: ["mystery", "thriller", "drama"],
    moods: ["dark", "intense", "smart", "emotional"],
    platforms: ["netflix", "prime video"],
    isLatest: false,
    isTrending: true,
    palette: ["#b3473f", "#e5bd8d", "#271718"],
    hook: "A gripping mystery powered by tension, atmosphere, and a superb central performance.",
    synopsis: "A pregnant woman searches Kolkata for her missing husband and uncovers a deadly conspiracy."
  },
  {
    id: "3-idiots",
    title: "3 Idiots",
    type: "movie",
    industry: "Bollywood",
    year: 2009,
    rating: 8.4,
    runtime: 170,
    language: "Hindi",
    genres: ["comedy", "drama"],
    moods: ["funny", "inspirational", "feel-good", "emotional"],
    platforms: ["netflix", "prime video"],
    isLatest: false,
    isTrending: true,
    palette: ["#77b6e8", "#f2d16c", "#2a3348"],
    hook: "Funny, warm, and surprisingly moving with a message that still lands.",
    synopsis: "Three engineering students push back against pressure, conformity, and a system built to break them."
  },
  {
    id: "rocky-aur-rani",
    title: "Rocky Aur Rani Kii Prem Kahaani",
    type: "movie",
    industry: "Bollywood",
    year: 2023,
    rating: 6.9,
    runtime: 168,
    language: "Hindi",
    genres: ["romance", "drama", "comedy"],
    moods: ["romantic", "stylish", "feel-good", "funny"],
    platforms: ["prime video"],
    isLatest: true,
    isTrending: true,
    palette: ["#ec5a7c", "#f7c35e", "#4b1836"],
    hook: "A glossy, colorful romantic drama with big charm and even bigger feelings.",
    synopsis: "A spirited couple swaps families to prove their love can survive culture clashes and chaos."
  },
  {
    id: "kill",
    title: "Kill",
    type: "movie",
    industry: "Bollywood",
    year: 2024,
    rating: 7.7,
    runtime: 105,
    language: "Hindi",
    genres: ["action", "thriller", "crime"],
    moods: ["dark", "intense", "energetic", "adventurous"],
    platforms: ["disney+"],
    isLatest: true,
    isTrending: true,
    palette: ["#b53b2f", "#c8c1b3", "#191211"],
    hook: "Lean, brutal, and relentless if you want an adrenaline-heavy Indian action pick.",
    synopsis: "An elite commando faces a train full of ruthless attackers in a single escalating night."
  },
  {
    id: "queen-gambit",
    title: "The Queen's Gambit",
    type: "series",
    industry: "Hollywood",
    year: 2020,
    rating: 8.5,
    runtime: 60,
    language: "English",
    genres: ["drama"],
    moods: ["smart", "stylish", "inspirational", "intense"],
    platforms: ["netflix"],
    isLatest: false,
    isTrending: true,
    palette: ["#7c2f2f", "#d4b483", "#26151b"],
    hook: "A sharp binge if you want elegant storytelling with high-stakes focus.",
    synopsis: "A young chess prodigy battles genius, addiction, and the cost of obsession."
  },
  {
    id: "stranger-things",
    title: "Stranger Things",
    type: "series",
    industry: "Hollywood",
    year: 2016,
    rating: 8.6,
    runtime: 50,
    language: "English",
    genres: ["sci-fi", "horror", "adventure"],
    moods: ["nostalgic", "spooky", "adventurous", "funny"],
    platforms: ["netflix"],
    isLatest: false,
    isTrending: true,
    palette: ["#ff654e", "#1f2e6b", "#140d17"],
    hook: "Perfect when you want eerie mystery wrapped in heartfelt adventure.",
    synopsis: "A group of friends uncovers supernatural secrets in their small town."
  },
  {
    id: "bridgerton",
    title: "Bridgerton",
    type: "series",
    industry: "Hollywood",
    year: 2020,
    rating: 7.4,
    runtime: 58,
    language: "English",
    genres: ["romance", "drama"],
    moods: ["romantic", "stylish", "escapist", "feel-good"],
    platforms: ["netflix"],
    isLatest: true,
    isTrending: true,
    palette: ["#8a4a7d", "#f3c8a2", "#331a2d"],
    hook: "Lavish, dramatic, and ideal for a glossy romantic binge.",
    synopsis: "Love, scandal, and status collide in a luxurious Regency-era social season."
  },
  {
    id: "three-body-problem",
    title: "3 Body Problem",
    type: "series",
    industry: "Hollywood",
    year: 2024,
    rating: 7.6,
    runtime: 55,
    language: "English",
    genres: ["sci-fi", "mystery", "drama"],
    moods: ["mind-bending", "dark", "intense", "smart"],
    platforms: ["netflix"],
    isLatest: true,
    isTrending: true,
    palette: ["#24a0b5", "#0f2636", "#d7ecf5"],
    hook: "A cerebral sci-fi mystery with huge ideas and serious tension.",
    synopsis: "A string of strange events pushes scientists toward a reality-altering revelation."
  },
  {
    id: "the-bear",
    title: "The Bear",
    type: "series",
    industry: "Hollywood",
    year: 2022,
    rating: 8.6,
    runtime: 35,
    language: "English",
    genres: ["drama", "comedy"],
    moods: ["intense", "inspirational", "funny", "emotional"],
    platforms: ["disney+", "hulu"],
    isLatest: true,
    isTrending: true,
    palette: ["#ef884b", "#4e2e24", "#f0d2b8"],
    hook: "Fast, emotional, and wildly alive if you want a high-pressure binge.",
    synopsis: "A brilliant chef returns home to rebuild a chaotic family sandwich shop."
  },
  {
    id: "dark",
    title: "Dark",
    type: "series",
    industry: "International",
    year: 2017,
    rating: 8.7,
    runtime: 55,
    language: "German",
    genres: ["sci-fi", "mystery", "thriller"],
    moods: ["mind-bending", "dark", "intense", "smart"],
    platforms: ["netflix"],
    isLatest: false,
    isTrending: true,
    palette: ["#2f473f", "#89a38f", "#151717"],
    hook: "A masterclass in moody, complex sci-fi mystery.",
    synopsis: "Disappearances in a small town reveal a labyrinth of time, family, and fate."
  },
  {
    id: "shogun",
    title: "Shogun",
    type: "series",
    industry: "International",
    year: 2024,
    rating: 8.8,
    runtime: 60,
    language: "Japanese / English",
    genres: ["drama", "history", "war"],
    moods: ["epic", "intense", "dark", "prestige"],
    platforms: ["disney+", "hulu"],
    isLatest: true,
    isTrending: true,
    palette: ["#d54d34", "#f1cf96", "#231414"],
    hook: "Prestige storytelling with breathtaking scale and political depth.",
    synopsis: "Power, loyalty, and survival collide in feudal Japan as rival forces reshape history."
  },
  {
    id: "arcane",
    title: "Arcane",
    type: "series",
    industry: "Hollywood",
    year: 2021,
    rating: 9.0,
    runtime: 42,
    language: "English",
    genres: ["animation", "action", "fantasy"],
    moods: ["intense", "stylish", "emotional", "adventurous"],
    platforms: ["netflix"],
    isLatest: true,
    isTrending: true,
    palette: ["#4ba2de", "#ec9b36", "#151522"],
    hook: "Visually explosive and emotionally rich with genuine depth.",
    synopsis: "Two sisters are pushed to opposite sides of a city divided by power and invention."
  },
  {
    id: "panchayat",
    title: "Panchayat",
    type: "series",
    industry: "Indian",
    year: 2024,
    rating: 8.8,
    runtime: 36,
    language: "Hindi",
    genres: ["comedy", "drama"],
    moods: ["feel-good", "cozy", "funny", "smart"],
    platforms: ["prime video"],
    isLatest: true,
    isTrending: true,
    palette: ["#6ab46d", "#e7ce8d", "#1f2a1d"],
    hook: "Easygoing, funny, and deeply lovable with a lived-in Indian charm.",
    synopsis: "A reluctant city graduate works in a small village and slowly gets pulled into its everyday emotional drama."
  },
  {
    id: "the-family-man",
    title: "The Family Man",
    type: "series",
    industry: "Indian",
    year: 2021,
    rating: 8.7,
    runtime: 45,
    language: "Hindi",
    genres: ["action", "thriller", "drama"],
    moods: ["intense", "smart", "dark", "funny"],
    platforms: ["prime video"],
    isLatest: true,
    isTrending: true,
    palette: ["#c07e39", "#e1cb96", "#1f1c20"],
    hook: "A sharp Indian thriller that balances spy tension with family chaos beautifully.",
    synopsis: "A middle-class man secretly working as an intelligence officer tries to save the country and his home life."
  },
  {
    id: "sacred-games",
    title: "Sacred Games",
    type: "series",
    industry: "Indian",
    year: 2018,
    rating: 8.5,
    runtime: 50,
    language: "Hindi",
    genres: ["crime", "thriller", "drama"],
    moods: ["dark", "intense", "smart", "prestige"],
    platforms: ["netflix"],
    isLatest: false,
    isTrending: true,
    palette: ["#c27a3b", "#6b4132", "#130f11"],
    hook: "A gritty Indian crime epic with style, scale, and serious momentum.",
    synopsis: "A troubled cop and a notorious gangster become linked by a race against catastrophe in Mumbai."
  }
];

const highlightPrompts = [
  {
    label: "Latest on streaming",
    prompt: "Show me the latest movies and web series that feel exciting and premium."
  },
  {
    label: "Netflix binge night",
    prompt: "Recommend the best Netflix web series for a thrilling weekend binge."
  },
  {
    label: "Bollywood gems",
    prompt: "Recommend great Bollywood movies across feel-good, thriller, and romantic moods."
  },
  {
    label: "Mind-bending mix",
    prompt: "Give me mind-bending sci-fi and mystery movies or series."
  },
  {
    label: "Comfort picks",
    prompt: "Suggest feel-good comedy or romantic movies for tonight."
  },
  {
    label: "Dark prestige",
    prompt: "I want dark, intense, high-quality web series with strong storytelling."
  }
];

module.exports = {
  catalog,
  highlightPrompts
};
